"""Run the regression ladder traced and render one animation per case for the docs.

``bazel run //hardware/pnr:ladder_animations -- --python PY --kicad-python KPY --kicad-cli CLI
--library LIB`` runs ``run.py --trace --initial-pool --initial-starts 8 --initial-finalists 3
--seed 0`` into ``.yapnr/ladder/<run-id>`` (git-ignored), reruns a case that fails in pool mode
in the baseline configuration, renders every passing case to ``docs/animations/<case>.webp``
(800 px, at most 2.5 MB), the README case (the TLC555 blinker, the literal 555 flasher) to
``<case>.gif`` (640 px, at most 5 MB) and writes
``docs/animations/manifest.json`` and ``docs/animations/ladder-results.json`` (every case's
gate result, failed ones included, with KiCad's findings by rule, the placed parts'
compactness and, with ``--gloss``, the gloss stage's bends and length). ``--render-only RUN_DIR
[RUN_DIR ...]`` skips the ladder (no KiCad needed). A failed case is not rendered into the docs
unless ``--allow-failed``; its end card then shows KiCad's findings in red. The case titles live
here, so the fixtures stay unchanged. ``--runner-arg ARG`` (repeatable, e.g. ``--runner-arg=--compact
--runner-arg=--gloss``) passes one more argument to every ``run.py``; the options that shaped a
run (``--compact``, ``--compact-off``, ``--shrink``, ``--gloss``, ``--gloss-flag``, read back from
its provenance) are part of each animation's ``config`` in the manifest. The baseline fallback
reruns a failed case with the same ``--runner-arg`` list unless ``--fallback-runner-arg ARG``
(repeatable; ``--fallback-runner-arg=`` for none) names its own, e.g. a compact ladder whose
failed case falls back to the default mode with ``--fallback-runner-arg=--gloss``.
"""

from __future__ import annotations

import argparse
import datetime
import json
import os
import platform
import re
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent

TITLES = {
    "01-connector-led-2": "Connector + LED",
    "02-resistor-led-3": "Resistor + LED",
    "03-branched-leds-5": "Two LEDs",
    "04-inverter-leds-8": "Inverter indicators",
    "05-timer-led-10": "TLC555 blinker",
    "06-chaser-14": "Two-stage chaser",
    "07-chaser-20": "Five-stage chaser",
    "08-chaser-20-plane": "Five-stage chaser with plane",
}
# The README shows the 555 flasher (the request's words): the TLC555 blinker; the chasers are
# the fallbacks if its GIF missed the budget.
README_CASES = ("05-timer-led-10", "06-chaser-14", "07-chaser-20")
POOL = ["--initial-pool", "--initial-starts", "8", "--initial-finalists", "3"]
# run.py options recorded in an animation's ``config`` (read back from the run's provenance).
RUNNER_OPTIONS = (("compact", "--compact"), ("shrink", "--shrink"), ("gloss", "--gloss"))
# 3: the gloss stage's saved board plays as a before/after (pnr.animate.gloss).
RENDERER_VERSION = 3
PROFILE = re.compile(r"^# Generated by pnr\.fab_profile \(profile ([^)\s]+)\)", re.MULTILINE)


def repo_root():
    workspace = os.environ.get("BUILD_WORKSPACE_DIRECTORY")
    return Path(workspace) if workspace else HERE.parents[2]


def run_ladder(repo, out, args, extra, cases):
    command = [args.python, str(repo / "hardware/pnr/regression/run.py"), "--repo", str(repo)]
    command += ["--out", str(out), "--python", args.python, "--kicad-python", args.kicad_python]
    command += ["--kicad-cli", args.kicad_cli, "--library", str(args.library)]
    command += ["--timeout", str(args.timeout), "--seed", "0", "--trace"] + extra
    for case in cases:
        command += ["--case", case]
    # The runner bounds each stage; this bounds the whole ladder.
    budget = args.timeout * 8 * max(1, len(cases))
    return subprocess.run(command, cwd=repo, timeout=budget).returncode


def runner_options(provenance):
    """The run.py options of a run that change its boards (``--compact``, ``--compact-off``,
    ``--shrink``, ``--gloss``, ``--gloss-flag``), from its ``provenance.json`` arguments."""
    arguments = provenance.get("arguments", {})
    out = [flag for key, flag in RUNNER_OPTIONS if arguments.get(key)]
    for part in arguments.get("compact_off") or []:
        out += ["--compact-off", part]
    for item in arguments.get("gloss_flag") or []:
        out += ["--gloss-flag", item]
    return out


def cases_of(run):
    summary = json.loads((Path(run) / "summary.json").read_text())
    out = {}
    for result in summary["results"]:
        if result["seed"] != 0:
            continue
        directory = Path(result["directory"])
        out[result["case"]] = (
            directory if directory.is_absolute() else Path(run) / directory,
            result,
        )
    return out


def drc_rules(directory):
    """KiCad DRC findings of a case by rule name (by type when KiCad names no rule)."""
    from pnr.trace import drc_rules as by_rule

    path = Path(directory) / "drc.json"
    return by_rule(json.loads(path.read_text())) if path.is_file() else {}


def fab_profile(directory):
    """The fabrication profile of the saved board's custom rules (``None``: no ``.kicad_dru``)."""
    path = Path(directory) / "routed.kicad_dru"
    match = PROFILE.search(path.read_text()) if path.is_file() else None
    return match.group(1) if match else None


def gloss_result(result):
    """The gloss stage of a case (``run.py --gloss``) in ``ladder-results.json``: whether it
    kept its edits, its transactions and the eligible signal copper's bends and length before
    and after it (docs/design/gloss.md); ``None`` without the stage."""
    gloss = result.get("gloss")
    if not gloss:
        return None
    summary = gloss.get("summary") or {}
    before, after = summary.get("metrics_before") or {}, summary.get("metrics_after") or {}
    return dict(
        kept=bool(gloss.get("kept")),
        accepted=summary.get("accepted_transactions"),
        proposed=summary.get("proposed_transactions"),
        bends=[before.get("bends_total"), after.get("bends_total")],
        length_mm=[before.get("length_mm"), after.get("length_mm")],
    )


def case_result(case, directory, result, config, profile=None):
    """One case of ``ladder-results.json``: the design's size and the gate's result, no paths.
    ``fab_profile`` is the profile of the saved board's custom rules, else the run's;
    ``compactness`` the placed parts' measure (``result.json``) and ``gloss``
    :func:`gloss_result`."""
    design = json.loads((Path(directory) / "design.json").read_text())
    nets = {net for p in design["parts"] for net in p["pins"].values() if net}
    pnr = result.get("pnr") or {}
    copper = result.get("copper_length_mm")
    return dict(
        case=case,
        title=TITLES.get(case, case),
        description=design.get("description"),
        seed=result["seed"],
        config=config,
        parts=len(design["parts"]),
        nets=len(nets),
        layers=design["constraints"]["board"]["layers"],
        routed=bool(pnr.get("converged") and not pnr.get("unrouted") and not pnr.get("deferred")),
        passed=bool(result.get("passed")),
        reasons=list(result.get("reasons") or []),
        opens=result.get("opens"),
        violations=result.get("violations"),
        drc_rules=drc_rules(directory),
        fab_profile=fab_profile(directory) or profile,
        vias=result.get("vias"),
        tracks=result.get("tracks"),
        copper_length_mm=None if copper is None else round(copper, 2),
        seconds=round(result.get("elapsed_seconds") or 0.0, 1),
        selected_start=(pnr.get("initial_pool") or {}).get("selected"),
        compactness=result.get("compactness"),
        gloss=gloss_result(result),
        # The legalizer's motion from the global poses (pnr.place.motion), when recorded.
        **({"legal_motion": pnr["legal_motion"]} if pnr.get("legal_motion") else {}),
    )


def platform_name():
    return "%s-%s" % (sys.platform, platform.machine().lower())


def ladder_provenance(run, image=None, kicad=None):
    """What the ladder run itself recorded (``provenance.json``): the engine's commit (with
    ``engine_dirty`` for modified engine files), ``sources_sha256`` (the frozen sources, stable
    across a rebase), the fab profile and the platform it ran on; no paths."""
    doc = json.loads((Path(run) / "provenance.json").read_text())
    return dict(
        engine_revision=doc.get("engine_revision"),
        engine_dirty=doc.get("engine_dirty"),
        sources_sha256=doc.get("sources_sha256"),
        fab_profile=doc.get("fab_profile") or doc.get("pnr_environment", {}).get("PNR_FAB_PROFILE"),
        platform=doc.get("platform"),
        image=image,
        kicad=kicad,
    )


def fallback_arguments(args):
    """The baseline fallback's extra run.py arguments: ``--fallback-runner-arg``'s when
    given (empty values dropped), else ``--runner-arg``'s."""
    if args.fallback_runner_arg is None:
        return list(args.runner_arg)
    return [arg for arg in args.fallback_runner_arg if arg]


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--render-only", type=Path, nargs="+", metavar="RUN_DIR")
    ap.add_argument("--python", help="numerical Python (torch, numpy, pyyaml) for run.py")
    ap.add_argument("--kicad-python")
    ap.add_argument("--kicad-cli")
    ap.add_argument("--library", type=Path)
    ap.add_argument("--timeout", type=float, default=900)
    ap.add_argument("--case", action="append", default=[])
    ap.add_argument("--out", type=Path, help="animations directory (default docs/animations)")
    ap.add_argument("--run-dir", type=Path, help="ladder output (default .yapnr/ladder/<run-id>)")
    ap.add_argument("--no-baseline-fallback", action="store_true")
    ap.add_argument("--allow-failed", action="store_true")
    ap.add_argument("--max-seconds", type=float, default=22.0)
    ap.add_argument("--image", help="container image digest the ladder ran in (manifest)")
    ap.add_argument(
        "--runner-arg",
        action="append",
        default=[],
        metavar="ARG",
        help="one more run.py argument for every run (repeatable; e.g. --runner-arg=--compact)",
    )
    ap.add_argument(
        "--fallback-runner-arg",
        action="append",
        default=None,
        metavar="ARG",
        help=(
            "the baseline fallback's run.py arguments instead of --runner-arg's (repeatable; "
            "an empty value adds nothing, so --fallback-runner-arg= falls back to the default mode)"
        ),
    )
    a = ap.parse_args(argv)
    from pnr.animate.cli import render_animation
    from pnr.provenance import Trace

    repo = repo_root()
    runs = a.render_only
    if not runs:
        missing = [
            k for k in ("python", "kicad_python", "kicad_cli", "library") if not getattr(a, k)
        ]
        if missing:
            ap.error("the ladder needs --" + ", --".join(m.replace("_", "-") for m in missing))
        stamp = datetime.datetime.now(datetime.timezone.utc).strftime("%Y%m%d-%H%M%S")
        pool_run = a.run_dir or repo / ".yapnr" / "ladder" / ("animations-" + stamp)
        run_ladder(repo, pool_run, a, POOL + a.runner_arg, a.case)
        runs = [pool_run]
        failed = [c for c, (_d, r) in cases_of(pool_run).items() if not r["passed"]]
        if failed and not a.no_baseline_fallback:
            baseline = pool_run.parent / (pool_run.name + "-baseline")
            run_ladder(repo, baseline, a, fallback_arguments(a), failed)
            runs.append(baseline)
    chosen = {}
    for run in runs:
        provenance = json.loads((Path(run) / "provenance.json").read_text())
        pool = bool(provenance.get("arguments", {}).get("initial_pool"))
        for case, (directory, result) in sorted(cases_of(run).items()):
            if a.case and case not in a.case:
                continue
            if case in chosen and (chosen[case][1]["passed"] or not result["passed"]):
                continue
            config = (POOL if pool else []) + runner_options(provenance)
            chosen[case] = (directory, result, config, run)
    out = a.out or repo / "docs" / "animations"
    out.mkdir(parents=True, exist_ok=True)
    entries, kicad = [], None
    for case in sorted(chosen):
        directory, result, config, run = chosen[case]
        if not result["passed"] and not a.allow_failed:
            print("skip %s: failed the gate (%s)" % (case, ", ".join(result.get("reasons", []))))
            continue
        version = Path(run) / "kicad-version.txt"
        kicad = kicad or (version.read_text().strip() if version.is_file() else None)
        trace = Trace(Path(directory) / "trace")
        title = TITLES.get(case, case)
        entry = render_animation(
            trace,
            "webp",
            out / (case + ".webp"),
            width=800,
            max_seconds=a.max_seconds,
            budget_mb=2.5,
            title=title,
            allow_failed=a.allow_failed,
        )
        entry["config"] = config
        entries.append(entry)
        print(
            "%s: %d frames, %.1f s, %d bytes"
            % (entry["file"], entry["frames"], entry["seconds"], entry["bytes"])
        )
    readme = None
    for case in README_CASES:
        if case in chosen and (chosen[case][1]["passed"] or a.allow_failed):
            directory, _result, config, _run = chosen[case]
            entry = render_animation(
                Trace(Path(directory) / "trace"),
                "gif",
                out / (case + ".gif"),
                width=640,
                max_seconds=a.max_seconds,
                budget_mb=5.0,
                title=TITLES[case],
                allow_failed=a.allow_failed,
            )
            entry["config"] = config
            entries.append(entry)
            readme = dict(case=case, file=entry["file"])
            print(
                "%s: %d frames, %.1f s, %d bytes"
                % (entry["file"], entry["frames"], entry["seconds"], entry["bytes"])
            )
            break
    import PIL

    manifest = dict(
        schema="yapnr-animations-v1",
        generated=dict(
            ladder=ladder_provenance(runs[0], a.image, kicad),
            render=dict(
                date=datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%d"),
                renderer=RENDERER_VERSION,
                pillow=PIL.__version__,
                platform=platform_name(),
            ),
        ),
        animations=sorted(entries, key=lambda e: e["file"]),
        readme=readme,
    )
    (out / "manifest.json").write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n")
    results = dict(
        schema="yapnr-ladder-results-v1",
        generated=manifest["generated"],
        cases=[
            case_result(c, d, r, cfg, ladder_provenance(run)["fab_profile"])
            for c, (d, r, cfg, run) in sorted(chosen.items())
        ],
    )
    (out / "ladder-results.json").write_text(json.dumps(results, indent=2, sort_keys=True) + "\n")
    return 0 if entries else 1


if __name__ == "__main__":
    raise SystemExit(main())
